# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b67649d54facfbd880913116a5835eec4cdba563ee45beae80d514471db9ccfc3c0b4fe158ad8e0224bfde87dac83b3f3cf467005c74d9cbe71575a8761964e

test:
  secret_key_base: 03c1d1218c2609c38691ec3463268a5e67a2ef58ab01c466e855ffc9846941f66fc5344578926add7b94c21db51b7eee205f2f44bc958a2b98a3d66f3efd0ddc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
